#!/bin/sh
# Copyright (C) 2026 Jenna Nelson
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Install scansnap. Deliberately boring: it copies a Python package and writes
# a launcher, so it needs nothing but python3 and works the same on any distro.
#
# There is a pyproject.toml as well if you would rather use pip. This script
# exists because `pip install --user` is refused by default on Debian and
# Ubuntu (PEP 668, "externally managed environment"), and telling every user to
# build a virtualenv for a 60KB pure-Python tool is worse than copying files.
#
#   ./install.sh                    into ~/.local, plus a systemd --user unit
#   ./install.sh --prefix /usr/local    system-wide (run as root; no unit)
#   ./install.sh --uninstall
#
set -eu

PREFIX="${PREFIX:-$HOME/.local}"
UNIT=1
UNINSTALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix) PREFIX="$2"; shift 2 ;;
        --prefix=*) PREFIX="${1#*=}"; shift ;;
        --no-unit) UNIT=0; shift ;;
        --uninstall) UNINSTALL=1; shift ;;
        -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
done

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
LIBDIR="$PREFIX/lib/scansnap"
BIN="$PREFIX/bin/scansnap"
UNITDIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"

if [ "$UNINSTALL" = 1 ]; then
    if command -v systemctl >/dev/null 2>&1 && [ -f "$UNITDIR/scansnap.service" ]; then
        systemctl --user disable --now scansnap.service 2>/dev/null || true
        rm -f "$UNITDIR/scansnap.service"
        systemctl --user daemon-reload 2>/dev/null || true
    fi
    rm -f "$BIN"
    rm -rf "$LIBDIR"
    echo "removed. Your config and scans were left alone:"
    echo "  ${XDG_CONFIG_HOME:-$HOME/.config}/scansnap/config"
    exit 0
fi

command -v python3 >/dev/null 2>&1 || { echo "python3 is required" >&2; exit 1; }
python3 - <<'EOF' || { echo "python 3.9 or newer is required" >&2; exit 1; }
import sys
raise SystemExit(0 if sys.version_info >= (3, 9) else 1)
EOF

echo "installing to $PREFIX"
mkdir -p "$LIBDIR" "$PREFIX/bin"
rm -rf "$LIBDIR/scansnap"
cp -r "$HERE/scansnap" "$LIBDIR/scansnap"
find "$LIBDIR" -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true

HOOKDIR="$PREFIX/share/scansnap/hooks"
mkdir -p "$HOOKDIR"
for h in "$HERE"/hooks/*; do
    case "$h" in *README.md) continue ;; esac
    [ -f "$h" ] || continue
    cp "$h" "$HOOKDIR/" && chmod +x "$HOOKDIR/$(basename "$h")"
done
cp "$HERE/hooks/README.md" "$PREFIX/share/scansnap/hooks/README.md" 2>/dev/null || true
echo "  $HOOKDIR/  (example rename hooks)"

cat > "$BIN" <<EOF
#!/bin/sh
# Generated by install.sh; edit $LIBDIR/scansnap instead.
# -u keeps output unbuffered, so the journal shows a scan's progress live
# rather than in one lump when the daemon exits.
exec python3 -suP -c 'import sys; sys.path.insert(0, "$LIBDIR"); from scansnap.cli import main; sys.exit(main())' "\$@"
EOF
chmod +x "$BIN"
echo "  $BIN"

if [ "$UNIT" = 1 ] && command -v systemctl >/dev/null 2>&1 && [ -n "${HOME:-}" ]; then
    mkdir -p "$UNITDIR"
    sed "s|@BIN@|$BIN|" "$HERE/systemd/scansnap.service.in" > "$UNITDIR/scansnap.service"
    systemctl --user daemon-reload 2>/dev/null || true
    echo "  $UNITDIR/scansnap.service"
fi

case ":$PATH:" in
    *":$PREFIX/bin:"*) ;;
    *) echo; echo "NOTE: $PREFIX/bin is not on your PATH." ;;
esac

cat <<EOF

Next:
  scansnap config --write          create a config file to edit
  scansnap discover                find the scanner
  scansnap enrol                   put this machine in its host list
  scansnap status                  check what the scanner thinks

Then, on the scanner's panel, tap the host name at the top and pick this
machine. Finally:

  systemctl --user enable --now scansnap
  loginctl enable-linger \$USER     so it runs when you are not logged in
EOF
